### PR TITLE
Updated helm collector to leverage helm client for go

### PR DESCRIPTION
**Pull request by arnaud-tincelin**
Example of output object:
```json
[
  {
    "name": "happy-panda",
    "namespace": "test",
    "status": "deployed",
    "chart": "wordpress",
    "history": [
      {
        "lastDeployment": "2021-08-04T17:57:05.275284338+02:00",
        "description": "Install complete",
        "status": "deployed",
        "revision": 1,
        "appVersion": "5.8.0"
      }
    ]
  }
]
```

Other remarks:
- This new function lists & get history of all HR from all namespaces
- For the time being, there is no possibility to filter by namespace or chart name

### CODE REVIEW

**Comment by sophsoph321** [comment]
Thank you @arnaud-tincelin for making these changes. Has this code been tested. If yes, could you please share the image you used to test so that I can test it on my end in order to make sure that these code fixes work on the distros for our mvp: CAPZ, openshift, kind, and aks-engine? Thanks!

**Comment by arnaud-tincelin** [comment]
> Thank you @arnaud-tincelin for making these changes. Has this code been tested. If yes, could you please share the image you used to test so that I can test it on my end in order to make sure that these code fixes work on the distros for our mvp: CAPZ, openshift, kind, and aks-engine? Thanks!

@sophsoph321 yes the code has been tested against an AKS cluster. If you wish to test this code I suggest you run the test along the collector. That will save you some time (no need to re-deploy aks-periscope). To do so, go to the collector directory (aks-periscope/pkg/collector) and run `go test -v -run TestHelmCollector`
Please note that the test is expecting to find at least 1 helm release in the targeted cluster.
Of course we will release a docker image later on.

**Comment by Tatsinnit** [comment]
💡 This looks good, to me but I need to test it against my local image. I will deep dive into the code sometime tonight.

**Review by Tatsinnit — APPROVED** [review]
👍 Thanks, honestly I actually learned few things from this PR, so It looks good to me if we can please get a local test for this in terms of local image published and the behaviour is not changed.

Approving it, and will try and see I can test with local published image just to be sure. Thanks.

**Comment by Tatsinnit** [comment]
💡 Thanks @sophsoph321 and @arnaud-tincelin  - fyi @sophsoph321 - you can test is using this image `docker.io/tatsat/helm-client` if it helps. Thanks.

I will merge this soon, I have tested with AKS cluster and all looks good. 🙏

**Review by sophsoph321 — APPROVED** [review]
Approving this PR as I have tested the helm collector changes using the image Tats provided and they look good.

**Pull request merged**
